### ISSUE TITLE
Error when setting algebraic variable and equation

### ISSUE THREAD

**Issue by mvanlobensels** [do-mpc/do-mpc#101]
**Describe the bug**
```
    # States struct
    p_x   = model.set_variable('_x', 'p_x')              # X position
    p_y   = model.set_variable('_x', 'p_y')              # Y position

    # References struct
    p_x_ref   = model.set_variable('_tvp', 'p_x_ref')  # X position reference
    p_y_ref   = model.set_variable('_tvp', 'p_y_ref')  # Y position reference

    lateral_err = sqrt((p_x - p_x_ref)**2 + (p_y - p_y_ref)**2)
    model.set_variable('_z', 'lat_err')
    model.set_alg('lat_err', lateral_err)
```
When I do the following in `my template_mpc.py` I receive the following error:
```
Traceback (most recent call last):
  File "/home/mees/Documents/MSc/RO47005/project/pdm-project/main.py", line 11, in <module>
    Simulation(params)
  File "/home/mees/Documents/MSc/RO47005/project/pdm-project/simulator/simulation.py", line 23, in __init__
    self.simulate(self.x, self.y)
  File "/home/mees/Documents/MSc/RO47005/project/pdm-project/simulator/simulation.py", line 31, in simulate
    simulator = template_simulator(model)
  File "/home/mees/Documents/MSc/RO47005/project/pdm-project/controls/template_simulator.py", line 43, in template_simulator
    simulator.setup()
  File "/home/mees/Utilities/miniconda3/envs/tf2/lib/python3.7/site-packages/do_mpc/simulator.py", line 193, in setup
    self.simulator = integrator('simulator', self.integration_tool, dae,  opts)
  File "/home/mees/Utilities/miniconda3/envs/tf2/lib/python3.7/site-packages/casadi/casadi.py", line 14436, in integrator
    return _casadi.integrator(*args)
RuntimeError: .../casadi/core/function_internal.cpp:145: Error calling CvodesInterface::init for 'simulator':
.../casadi/core/integrator.cpp:314: Assertion "!sp_jac_dae_.is_singular()" failed:
Jacobian of the forward problem is structurally rank-deficient. sprank(J)=4<5
```

**Which version of do-mpc are using and how did you obtain it?**
- Installation via pip?
Yes
- Cloned from repository?
No

**Are you running our examples or your own code?**
My own code

**Screenshots**

**Which system are you working on?**
Linux

**Additional context**
It is quite unclear to me how I should properly set an algebraic equation. I need to constrain my lateral error for an MPC implementation.

**Comment by alexandru-tc** [comment]
Hey Mees,

actually what I would do, in your case, is to try to set  the lateral _err simply as a nonlinear constraint on your problem, so setting it in the template_mpc.py. Anyway this can be evaluated at any point based solely on your differential variables, and it makes it much more easy to handle. If your controller is having a tough time satisfying it, you can even decide to implement it as a soft constraint (probably not a bad idea to start with, either). I'm suggesting this because I've also done something similar before.

If you have proper algebraic states you have to take care of carefully initializing the optimizer and also the algebraic equations have to be satisfied at the major collocation points, etc.  We are currently working on full support for DAE systems in do-mpc, which does not work for continuous systems yet. Whenever you can reduce your system to an ODE system, I'd recommend you do that. 

Good luck optimizing!
Alex

**Comment by 4flixt** [comment]
Hey Mees,

I Agree with alexandru, there is no need for an algebraic state in this particular case. If you want to, you can use the method [set_alg](https://www.do-mpc.com/en/latest/api/do_mpc.model.Model.set_alg.html) in the model to store the expression on how to compute the lateral error. 

This expression can then be reused in the formulation of the MPC controller, e.g. as a constraint with [set_nl_cons](https://www.do-mpc.com/en/latest/api/do_mpc.controller.MPC.set_nl_cons.html)

Best
4flixt
