### ISSUE TITLE
Plot

### ISSUE THREAD

**Issue by HoussemCHAOUALI** [do-mpc/do-mpc#105]
Hello,
I am working on the code given below, I want to plot the generated output from the lines 111-120, As you can see in the first axis of the plot, the output is constant at 0 while the simulator output is varying as needed. 
1/ Am I plotting the desired output in  a wrong way.
2/ The States X plot (second axis), the MPC outut is negaive, although, the states limits are fixed between 0 and 100 (lines 99 and 102). Again, the simulator output shows that these bounds are respected but not the MPC output. 

Thanks in advance for your help.

[MPC.zip](https://github.com/do-mpc/do-mpc/files/5766645/MPC.zip)

**Comment by 4flixt** [comment]
Dear Houssem,

apologies for the late reply. In the code you sent I found a bug on our side (in the plotting engine) and a misconception from your side.

First about our bug: In our current implementation, it is important to first configure the figures and then to run the MPC/simulation loop. This is not ideal and not intended. I'll raise an issue to fix it. In the code I'll send you back this problem is solved.

The issue on your side is as follows:

For the MPC ``tvp`` you have the following code:
```python
def tvp_fun(t_now):
    d_value=[0, 0, 0, 0, 0, 0.300, 0.400, 0.420, 0.450, 0.532, 0.585, 0.600, 0.575, 0.600, 0.585, 0.535, 0.545, 0.455, 0.431, 0.355, 0.025, 0, 0, 0]

    for k in range(mpc.n_horizon):
        tvp_template['_tvp', k, 'd'] = d_value[k]

    return tvp_template


mpc.set_tvp_fun(tvp_fun)
```
and for the simulator you have:
```python
def tvp_fun(t_now):

        d_value = [0, 0, 0, 0, 0, 0.300, 0.400, 0.420, 0.450, 0.532, 0.585, 0.600, 0.575, 0.600, 0.585, 0.535, 0.545, 0.455, 0.431, 0.355, 0.025, 0, 0, 0]

        tvp_sim_template['d'] = d_value[int(t_now)]

        return tvp_sim_template


# Set the tvp_fun:
simulator.set_tvp_fun(tvp_fun)
```
where ``d_value`` seems to be the same sequence in both cases.

**Now the problem:** When you run the MPC controller in the first iteration, it will be handed the correct sequences of the future values of ``d`` that are also used in the simulator at the respective time steps. However, at the second and all following iterations, you pass the exact same sequence of  predicted ``tvp`` values as in the first iteration. To make that more clear: The controller will think that at any iteration ``k`` the current value of ``d`` is zero (first element of ``d_value``). The simulator, however, will use the "correct" value of ``d`` that also changes over time. 

In you case, this has the consequence that the controller violates the constraints at some point. Why? Because just before the violation the controller expects for the future the sequence of ``d_value`` starting with ``d=0`` and choses the input to avoid the constraints. This input is now passed to the simulator which simulates the system with a different value for ``d`` which leads to an unexpected next state which of course can also violate the constraints. 

**So how do you fix this?**
In the ``tvp_fun`` for the MPC controller you will need to slide along a window of ``tvp`` values which must be at least as long as the number of simulation steps + the prediction horizon. 

I hope this answer helped.

Best 
4flixt

**Comment by HoussemCHAOUALI** [comment]
Hello,
Tahnk you for your answer and sorry for this late reply.
We tried to use your solution to solve the problem, it seems to be working but I am not sure how to apply this to get the needed code.

1/ we defined 48 values for d_value , but it only works if the output is a constant. What we want to do, is to make the output of tvp_template an arry of 24 values at each iteration.
 Meaning: for example, if we are at the third iteration (simulation step =3), the output must be an array containing the 24 values starting from the third value of d_value. but this cannot be treated in the model equation(...-_p), it always return a sizing probelm (even if we change the shape to (24,1)). 


2/ besides, if we add a second tvp_template function, it interfaces with the first one even if we change the name of the function and the plot of the demand returns to 0 and the bounds are no longer respected. you can check this if you uncomment the lines of TVP_template_2 and make necessary changes for the plot lines.

I dont know if we are not using the tool correctly or if we are missing something. 

[Uploading MPC.zip…]()

**Comment by 4flixt** [comment]
Hi Houssem,

thank you for your question.

1) I think your test case works now. I found it much easier to see that once I turned your code into a very simple simulation:
[MPC1.py.zip](https://github.com/do-mpc/do-mpc/files/5794580/MPC1.py.zip)

2) There are several issues here:
- You add a new ``tvp`` (named ``_p2`` / ``alpha``) but is not used anywhere in your code (not in the rhs for example). It thus has no effect whatsoever.
- In your ``tvp_fun_2`` you only set the values for this new ``tvp`` the values of your other ``tvp`` therefore default to zero. To set both values you need to do something like this:

```python
def tvp_fun_2(t_now):
   ...
    for k in range(mpc.n_horizon):
      tvp_template_2['_tvp', k, 'alpha'] = ...
      tvp_template_2['_tvp', k, 'd'] = ..
```

Furthermore, I have to tell you that we are not going to continue this level of fine granular implementation aid. This is very time consuming from my side and and not beneficial for other users of the code base. Please take more time to look through your examples (it should be clear that variables have to be used in the model to have any effect) and our documentation before posting questions that should either be about the general understanding of do-mpc, potential bugs or feature requests.

Best
4flixt
