### ISSUE TITLE
Adding constraints to expressions

### ISSUE THREAD

**Issue by xholcaravan** [do-mpc/do-mpc#106]
I want to add constraints to a variable which can be obtained through computation of three state variables (_x). This variable is defined as (_aux) because it is not a state variable as such.

Using the CSTR [example](https://www.do-mpc.com/en/latest/example_gallery/CSTR.html) you provide, suppose you want to limit ``T_dif <= 2``. You can compute ``T_dif`` from the difference of two state variables: ``T_R`` and ``T_K``. 

The approach I tried was to create a new state variable T_dif_x. Then I need to define its ODE which I easily get from the ODE's of T_R and T_K
```python
model.set_rhs('x_T_dif',  ((K_1*C_a*H_R_ab + K_2*C_b*H_R_bc + K_3*(C_a**2)*H_R_ad)/(-Rou*Cp)) + F*(T_in-T_R) +(((K_w*A_R)*(-T_dif))/(Rou*Cp*V_R)) - (Q_dot + K_w*A_R*(T_dif))/(m_k*Cp_k))
```

Then to add the constraint I simply add 
```python
mpc.bounds['lower', '_x', 'x_T_dif'] = 2
```

But this doesn't work. [Edit: doesn't work in the sense that the solution exists, is computed and violates the bound in the line above.]

I just used the CSTR example to make it simpler to explain. My case is as follows: I need to limit the power output of a turbine, and this output is therefore a hard constraint.

**Comment by 4flixt** [comment]
Dear xholcaravan,

thank you for your question. I would really appreciate if you could longer code blocks with markdown. This makes it way easier to read.

Regarding your question: I would strongly advise you to not use the artificial state variable you introduced above. The expected approach for your problem is to use [mpc.set_nl_cons](https://www.do-mpc.com/en/latest/api/do_mpc.controller.MPC.set_nl_cons.html). With this method you can add arbitrary constraints to your problem consisting of any expression. The ``aux`` variables are exactly that: An expression and can thus be used in this method. 

Note that ``set_nl_cons`` only support ``expr <= ub`` (ub=upper bound), so if you need an upper and a lower bound (lb), we ask you to call the method twice with:

```
expr <= ub
-expr <= lb
```

So if you have introduced the variable ``T_diff`` as an ``aux`` in the model you can simply do the following:
```python
mpc.set_nl_cons('temp_diff', model.aux['T_diff'], ub = 10)
```

Note that it is optional to introduce ``aux`` in the model. You can also just retrieve the states at that point and write an expression:
```python
mpc.set_nl_cons('temp_diff', model.x['T_R']-model.x['T_K'], ub = 10)
```

Hope that helps. Best 4flixt
