### ISSUE TITLE
How to define a dynamic objective function?

### ISSUE THREAD

**Issue by TheCodeSummoner** [do-mpc/do-mpc#109]
This is more of a generic question (or a feature request) than the documentation issue.

I was wondering if it's possible to change the objective function at runtime. If so, this should be documented as this is not immediately obvious.

Let's say I'm encoding some vehicle motion problem into MPC, and I want to steer the vehicle towards a point `P = (x, y)`. Let's now assume I want to change `P` at runtime, and steer the vehicle towards a different point `P' = (x', y')` (everything else stays the same). I don't know how to do it with `do_mpc`.

I have considered the following approaches:

- I thought there might be some `parameter` variable type I can set on the model, and update its value when I need it. Then the objective function would be for example `(target_point - current_position)**2` - based on distance with respect to the parametrised target point. It seems that the `_p` variable type is a different type of parameter, and doesn't allow this scenario.
- I also thought that perhaps I can set the Meyer Term to use some sort of getter, like a `property`. Then the relevant code would become `mterm=meyer_term_getter`, and the getter's functionality would return the proper variable when needed.

Neither of the solutions worked, and I'm not at all knowledgeable in underlying code structure or relevant libraries, to adjust the functionality (at least as of now, I started using the tool a few days ago).

Therefore, I kindly ask for your assistance :)

**Comment by 4flixt** [comment]
Dear CodeSummoner,

thank you for your question. For exactly this purpose we have implemented in do-mpc the so called "time-varying parameters" (tvp).  [Here](https://www.do-mpc.com/en/latest/FAQ.html#time-varying-parameters) is an article on how to use them.

For your example:
1) Introduce ``target_point`` as a variable in the ``model`` and choose type ``tvp``. You wont need this parameter in the model itself.
2) When configuring the ``MPC`` class, use ``target_point`` in the cost function.
3) Add the ``tvp_fun`` to the MPC class. This function takes as input the current time and has to populate a structure with the future values of the ``target_point``.
4) The simulator also needs to know about the ``tvp`` by passing the simulator ``tvp_fun``. However, since ``target_point`` won't affect the model integration, the ``tvp_fun`` can just return the default structure with all elements set to zero. 

Note that ``tvp`` are also used for external parameters affecting the model (e.g. wind speed). In that case the simulator ``tvp_fun`` should also return the correct values. 

I hope that helped. Feel free to close this issue if your question has been answered.

Best
4flixt

**Comment by TheCodeSummoner** [comment]
Thank you for the explanation, I've been confused a little with what the time-varying parameter does, it's super clear now - and it is also exactly what I was looking for!

**Comment by patelsid21195** [comment]
> Thank you for the explanation, I've been confused a little with what the time-varying parameter does, it's super clear now - and it is also exactly what I was looking for!

Hey, I am dealing with similar kind of problem where I need to let MPC track the different set-points at every 200 time-steps and I am super confused with tvp, could you please explain me how should I approach to solve that ? 

Thanks in advance

**Comment by 4flixt** [comment]
Hi @patelsid21195,

did you read the article on time-varying parameters referenced above? If you still have a question, please post it to the discussions forum and please be a bit more specific.

Best 
4flixt
