### ISSUE TITLE
bang bang control (binary or discrete value input) support

### ISSUE THREAD

**Issue by tf1991-06** [do-mpc/do-mpc#112]
In a practical situation, I believe that do-mpc must support binary (or discrete) values.
For example, there are many binary control variables in a plant, such as a valve.
Is there any possibility to extend the do-mpc solver to integer optimization problems?

**Comment by 4flixt** [comment]
Hi @tf1991-06,

I agree that this feature would be super useful but unfortunately it is currently not supported. 
The changes are manageable since we interface CasADi which in turn interfaces e.g. bonmin and knitro. 
We will hopefully have to time to look into it in the future. I'll add an issue for ourselves. 

Best
4flixt
