### ISSUE TITLE
set_nl_cons: Option to have just a single slack variable for the entire horizon

### ISSUE THREAD

**Issue by 4flixt** [do-mpc/do-mpc#149]
**Is your feature request related to a problem? Please describe.**
See discussion #148 

**Proposed change:**
``set_nl_cons`` with active soft constraints option introduces a new slack variable for each time-step of the horizon. In some cases it might be beneficial to introduce just a single slack variable, e.g.:
- to reduce computational complexity
- appraoch in discussion #148

This could be a simple flag in this method and must be considered when configuring the optimization problem in MPC and MHE.

**Comment by cahly** [comment]
Great! Looking forward to it. In the meantime i found an insane workaround that added considerable complexity invoving a new state and a new input. It will be great to do it right. Thanks for the quick response.

BR

**Comment by 4flixt** [comment]
Sounds interesting! Feel free to share it if you like :)

**Comment by cahly** [comment]
OK, but you have been warned that it is ugly. And it only works with positive quantities.

# state I am interested in minimizing the max of
x = model.set_variable(var_type='_x', var_name='x')

# additional state that keeps track of the max of x
x_max = model.set_variable(var_type='_x', var_name='x_max')

#an input that keeps will end up minimized but above 0 and above the change in the max of x
x_change = model.set_variable(var_type='_u', var_name='x_change ') 

#minimize the end state of x_max, which is the same as minimizing the integral of x_change
# which is the same as minimizing the max of x
J=model.set_expression(expr_name='J',expr=k*x_max/(horizonLength*sampleTime))
mpc.set_objective(lterm = ... ,mterm= J)

#essentially make x_max the integral of x_change
model.set_rhs('x_max',x_change)

#make   x - x_max < x_change essentially setting x - x_max = x_change because anything else would be more expensive
mpc.set_nl_cons(expr_name='x_change_limiter',expr=-x_change + x_max ,ub=0,soft_constraint=False)

#dont allow x_change to be negative as this would start to ignore the largest x seen previously 
mpc.bounds['lower','_u','x_change'] = 0

There you go. All that could be solved with a single slack variable ;) This still runs ok for my problem, but x_change makes the problem very semidefinite, as many different x_change vectors gives the same optimum as long as the sum is the same, and some other constraints, but still.

**Comment by 4flixt** [comment]
Also make this clear in the documentation (https://www.do-mpc.com/en/latest/api/do_mpc.controller.MPC.set_nl_cons.html)
use indices ``_k``

**Comment by cahly** [comment]
I see you made the feature urgent. Thank you! I just want to let you know that i think you are doing awesome work that you provide for free, and i appreciate it a lot.

**Comment by frapaoli** [comment]
Hi everyone, I'm using the do-mpc library and I have the same need (define a single slack-variable for the entire horizon). I read this issue and the [discussion](https://github.com/do-mpc/do-mpc/discussions/148) that originated it, but I cannot find a way to implement the single slack-variable by using the API. Has it been implemented?

**Comment by 4flixt** [comment]
Hi @frapaoli ,

I think the documentation should be clearer about this feature. You can choose to have a single slack variable for the entire horizon by setting:

```
mpc.settings.nl_cons_single_slack = True
```

This changes the behavior for all nonlinear constraints, however.

Best,
4flixt

**Comment by frapaoli** [comment]
Hi @4flixt ,
Thank you for the quick reply. Even if it changes the behavior for all nonlinear constraints, this feature is very useful.

Is there any way to introduce this "single slack-variable" behavior only for certain constraints? If not, I guess I can use your suggestion to implement single slack-variables and, for constraints where I need a slack-variable for each time step, I can implement the slack-variables as MPC inputs.

**Comment by 4flixt** [comment]
Unfortunately this choice is global and in the current version it is not possible to have an individual selection for each nonlinear constraint. I have added a feature request. Maybe this can be improved in a future version.
