### ISSUE TITLE
saving MPC object

### ISSUE THREAD

**Issue by talebbh12** [do-mpc/do-mpc#158]
Hello, 
I am trying to save the mpc object from one trial to another, but pickling is not working due to a SwigPyCasadiObject, any recommendation?

Best Regards, 
Taleb BOU HAMDAN

**Comment by 4flixt** [comment]
Hi @talebbh12,

the entire MPC object cannot be pickled unfortunately. This is nothing we can fix as it is blocked by a CasADi object (in particular the optimizer). So we can also not delete it because this would make saving obsolete. 
You can only pickle the ``mpc.data`` object. 

Sorry that I can't help any further.

Best
4flixt

**Comment by 4flixt** [comment]
No it only saves the resulting trajectories and predictions.
