### ISSUE TITLE
Getting worse results with n_robust= 1 

### ISSUE THREAD

**Issue by malekern** [do-mpc/do-mpc#22]
Can somebody please tell me why I do get worst results with n_robust =1 . Its in the optimizer and ive tried n_robust = 0,1,2,3,4,5 and actually i have no clue why 1 would be the worst. 
I would be very glad if someone could explain that to me. 
Iam working on some kind of trajectory planning.
Friendly regards 
Maxim

**Comment by alexandru-tc** [comment]
Dear Maxim,

Thanks for sharing your experience. First I'd like to know how you set up
your multi-stage nmpc, that is, what are your uncertain parameters. How do
you define the uncertainty levels and what are the real parameters you
apply in the simulation? Please keep in mind that the first value in the
uncertainty vector should be the nominal one.
Next is the observation that, under nominal conditions, robust nmpc should
be expected to behave "worse", especially for a reference tracking problem.
That is typically caused by the inherent conservatism that this method has:
the control inputs it produces are a result of a multi-scenario problem,
and so they are calculated to realize a compromise between the scenarios.
It's interesting that higher levels of uncertainty return better results,
I'd be curious to see the problem you solve.
Please give me some more detail and we can discuss further.

Cheers,
Alex

**Comment by malekern** [comment]
Hello Alex,
Thanks for your help and the fast answer.
You can have a look at the code here.
https://gist.github.com/malekern/39854bcbc99d224be85464842e19fe43
"

> How do you define the uncertainty levels

" 
Acutally I don´t know how to do this the proper way.
What you say about the conservatism and the uncertainty makes sense to me. Atleast the difference
between n_robust=0 and n_robust=1.
I am testing this code to improve it and iam trying to get it more stable. Thats why I always test a couple of starting points in a row. In the Gist I also have commented the robust test results.
Friendly regards 
Maxim

**Comment by alexandru-tc** [comment]
Hello again Maxim,

I did not have too much time to analyze your implementation, let alone to
run it on my PC... But let me see if I managed to get a correct idea of
what you are doing: you are using a model predictive control schem to
identify optimal routes from a varying start point to a destination area
(parking spot maybe?), which you define by nonlinear constraints. It's an
intersting way to put it, something tha we at the TU Dortmund don't really
have experience with, although we have used do-mpc for dynamic vehicle
control (some AGVs and also a model race car on a track). Our applications
are usually of a different kind.

One thing I didn't see was how you used your uncertain parameter "noise".
Usually we define possibly uncertain model parameters ( in the _p vector),
to which we then attribute uncertainty levels (in the uncertainty_values
vector). These parameters impact the model ODEs, and the robust NMPC is
geared exactly at analyzing the effect of these parameters on the
prediction. Since your parameter does not affect the model, it is here
useless. regardless, the NLP problem will still branch on these paramneters
and you will have a problem with 2, 4, 8, 16 or 32 scenarios. Given the
size of your model, I don't actually expect this to run into memory issues
or significant slowdown, but it is still an intersting question: what doe
sthe optimizer solve, if there are 32 scenarios which are essentially
equal? And why should this then be different from n_robust = 1 to 5 ?? To
my mind, it shouldn't matter anyway, although I don't see the use of a
robust scenario here...

Are all your simulations solved by the optimizer? Does Ipopt always exit
with an optimal solution found message? Additionally, given your problem, I
expect unsuccessfull runs to be mainly due to the limite dprediction
horizon or simulation time. Maybe a failed run simply means that the
optimizer could not find a solution from the given starting point in only
50 seconds and with only 10 seconds of "ahead vision", since some positions
require a longer trajectory. Could this be a case? Do keep me updated, I
really like your application and I hope you will be successful in solving
it :)

Have a nice weekend!
Alex

**Comment by malekern** [comment]
Hello Alexandru,
Again thanks for you effort.
Yes you understood  pretty well what I´am trying to do.

Thanks for the advice about the uncertain parameters. Iam testing them . 
What you did mention about the robustness makes sense to me.
I got one more question about the horizon. I thought that the higher the horizon is set, the higher the chance to get a solution. But in my testings I keep getting the best results for horizons arround  10 and iam getting worse results for higher horizon values. Does this make any sense?  You basically say that my time end could be a problem as well? I checked it and a higher time_end value actually had a little positive impact on my results. 
Greetings Maxim
