### ISSUE TITLE
Updating Bounds

### ISSUE THREAD

**Issue by pmusau17** [do-mpc/do-mpc#221]
Is it possible to update the bounds at runtime without calling setup? Or does changing the bounds force to recall setup?

**Comment by pmusau17** [comment]
Figured out you can do this by using tvp's and set_nl_cons()

**Comment by 4flixt** [comment]
Hi @pmusau17, great that you found a solution yourself !

Alternatively, you can update the properties ``mpc.lb_opt_x`` and ``mpc.ub_opt_x``. They are indexed in the same way as [opt_x](https://www.do-mpc.com/en/latest/api/do_mpc.controller.MPC.opt_x.html). Notice that these properties are created during ``mpc.setup()``.

The feature is not public facing supported since it is easy to break things but I guess it is worth a try.

Also: feel free to open a [discussion](https://github.com/do-mpc/do-mpc/discussions) next time instead of an issue (unless you have found a concrete error or wish for a specific feature).

Best
4flixt
