### ISSUE TITLE
No uncertainty

### ISSUE THREAD

**Issue by hxlee309** [do-mpc/do-mpc#25]
Hi,

When I try to compile my model with no uncertainty (_p = vertcat([])), it returns the follow error: 

Traceback (most recent call last):
  File "do-mpc.py", line 64, in <module>
    configuration_1.setup_solver()
  File "../../code/core_do_mpc.py", line 190, in setup_solver
    nlp_dict_out = setup_nlp.setup_nlp(self.model, self.optimizer)
  File "../../code/setup_nlp.py", line 379, in setup_nlp
    branch_offset[k][s] = 0
IndexError: index 0 is out of bounds for axis 0 with size 0

Please let me know the correct way of compiling the model with no uncertainty.

Thanks,

Hanxiang

**Comment by sergiolucia** [comment]
Hi Hanxiang,

the easiest way to solve this problem is to always define some uncertain parameters, even if you do not use them.
Since do-mpc is thought for robust NMPC it might give some problems if you do not define any...
Just define them as in the examples but do not use those symbols in your equations. Then when you use n_robust = 0 you will have your nominal NMPC.

Best,
Sergio
