### ISSUE TITLE
Install New Linear Solver

### ISSUE THREAD

**Issue by hxlee309** [do-mpc/do-mpc#28]
If I want to use new linear solver (i.e. MA27, MA57, MA97), how should I install them?

**Comment by alexandru-tc** [comment]
In order to use other linear solvers, IPOPT should be able to load them. The likes of MA27 and other HSL solvers can be obtained from a shared library or they can be compiled from sources on your machine. At this point the question is: are you using a WIndows environment or something Unix like? In the first situation, the answer is rather unpleasant: it will be almost impossible to get it working, especially if you don't have experience with compilers and the linking system. You could try to use a precompiled dll file, but that won't work for the newer versions of CasADi (post v2.4) and the hassle doesn't really make up for it. 

If, however, you are using Linux or Mac, compiling the solvers yourself won't be a problem. Just download them from [here](http://www.hsl.rl.ac.uk/ipopt/) and follow the steps [here](https://github.com/casadi/casadi/wiki/InstallationLinux) so nicely explained by the CasADi developers in order to get them running. At the end of the day, this is a CasADi + IPOPT issue, so you have to have this sorted out before you can use the do-mpc platform.

Hope all goes well!
Alex

**Comment by Flancis** [comment]
Hi,

This is really a nice tool.

On the Windows environment, the HSL solvers can be installed by using MINGW64. The following instructions from the CasADi group worked for me.
https://groups.google.com/forum/#!searchin/casadi-users/hsl%7Csort:date/casadi-users/kkGih1yKS-o/yV8zdyqvDQAJ

Francis

**Comment by sergiolucia** [comment]
Hi Francis, 

thanks a lot for sharing! This will indeed help many people!

Best regards,
Sergio

**Comment by 4flixt** [comment]
We will adress the issue in the new **do-mpc** [documentation](www.do-mpc.com). See issue #45 .
