### ISSUE TITLE
Time varying parameters again!

### ISSUE THREAD

**Issue by halakoom** [do-mpc/do-mpc#378]
Hi I'm trying to set a time-varying parameter in my MPC and keep getting error for setting up the tvp for the simulator.
here's what I did:
I defined a time array as t = np.linspace(0,240,241)
then created an array of my time-varying parameters as: 
def q1(t):
    return 0.11*t+56 if t<=120 else 69
and put them all in a data frame called demand as:
demand['q1'] = [q1(i) for i in t]

def tvp_temp(t_now):
    for k in range(mpc.n_horizon+1):
        tvp_template['_tvp',k,'q1'] = demand.q1[t_now+k]
    return tvp_template
mpc.set_tvp_fun(tvp_temp)

So far so good! however, when I do the same for the simulator as:
tvp_template_sim = simulator.get_tvp_template()
def tvp_temp_fun_sim(t_now):
    tvp_template_sim['q1'] = demand.q1[t_now]
    return tvp_template_sim
simulator.set_tvp_fun(tvp_temp_fun_sim)

I get the following error
Exception: Unknown keyword '_tvp'. Available entries: ['default', 'q1', 'q2']

The above exception was the direct cause of the following exception:

Exception: Error occured in struct context with powerIndex ('_tvp', 0, 'q1'), at canonicalIndex ()

I tried the following trick to get rid of indexing problem but didn't work:
def tvp_temp_fun_sim(t_now):
    tvp_template_sim['q1'] = demand.q1
    return tvp_template_sim
simulator.set_tvp_fun(tvp_temp_fun_sim)

**Comment by 4flixt** [comment]
Hi @halakoom,

the error message seems quite clear to me. You are using the index ``'_tvp', 'q1'`` on the struct where only `'q1'` would be neccessary. 
Unfortunately, the interface to the `tvp_template` is slightly different for the controller and the simulator. That is the case, because the simulator only needs the current value whereas the (MPC) controller requires the future trajectory.

Best,
4flixt
