### ISSUE TITLE
MHE: Optimization starts at last collocation point of the first interval

### ISSUE THREAD

**Issue by davidzanger** [do-mpc/do-mpc#398]
Describe the bug
In do_mpc/estimator/_mhe.py in the method _prepare_nlp() the arrival cost (cost for the initial state) is calculated using the last collocation point of the first interval:
```python
arrival_cost = self.arrival_cost_fun(
    opt_x_unscaled['_x', 0, -1],
    opt_p['_x_prev'],#/self._x_scaling,
    opt_x_unscaled['_p_est'],
    opt_p['_p_est_prev'],#/self._p_est_scaling
    opt_p['_p_set']
    )
```
Shouldn't it start with `opt_x_unscaled['_x', 0, 0]`? However, `opt_x_unscaled['_x', 0, 0]` is not even in the equality constraints. If you look at the values of the first collocation interval, they always stay the same and are not optimized.

**Comment by Mrfeli01** [comment]
Dear @davidzanger,
this implementation is actually correct, albeit a bit confusing.
We provide more informatin about this behaviour in the documentation of the attribute [opt_x](https://www.do-mpc.com/en/latest/api/do_mpc.controller.MPC.html#opt-x) (Note: `opt_x` behaves similarly for the mpc controller and is better documented in this case)

In a nutshell, `opt_x['_x', k, b, -1]` returns the first element of the states of timestep `k` for scenario `b`. This is because for a given scenario there is only one connection leading to that point, but multiple branches (scenarios) leading away from that point. See also the figure that is shown in the documentation for `opt_x`.

Notice that this behaviour doesent make a lot of sense for the MHE (there is only one scenario), however, we inherit the behaviour from the class optimizer that is shared between MHE and MPC.

FInal remark: Since there are no collocation points before the first timestep, these variables are unused. 

Best
Mrfeli
