### ISSUE TITLE
Adaptive horizon

### ISSUE THREAD

**Issue by eivindeb** [do-mpc/do-mpc#94]
I am working on an application using adaptive horizon MPC, i.e. the horizon length is a function of the state and will (possibly) change at every time step. So far I have tried constructing a new MPC object with a new value of the n_horizon parameter every time the horizon changes, however, this leads to a large increase in runtime (>10x). 

Is there a better way to implement adaptive horizon in do-mpc?

Also, is it possible to set the terminal cost (mterm) to a non-static function evaluated at run time, e.g. a trainable neural network that maps from state x to scalar value?

**Comment by 4flixt** [comment]
Hi eivindeb,

thank you for your question. The MPC implementation you are trying to achieve isn't natively supported by do-mpc. The problem is that the structure of the optimization problem changes when changing the number of steps in the prediction horizon. Essentially, this requires to recreate the MPC object from scratch, just like you did it and with the large increase in runtime. 

Maybe you can try an alternative approach, however: Keep the prediction horizon constant and vary the time-step for each of these steps? If you are using a continuous-time model you can essentially just scale the right-hand-side with a varying time-step. You may wont to use time-varying parameters (tvp) in do-mpc for this kind of implementation. I don't know about your particular problem but this approach can often lead to good results in similar scenarios as the one that you described. 

I hope that helped.

Best,
4flixt

**Comment by eivindeb** [comment]
Hi 4flixt,

I see, thank you for the suggestion! 

Do you have any idea if it is possible to set the terminal cost (mterm) to a non-static function evaluated at run time, e.g. a trainable neural network that maps from state x to scalar value?

**Comment by 4flixt** [comment]
If the neural network is already trained, you can of course evaluate it with the terminal state. Unfortunately, you can not directly evaluate e.g. a keras/tf model with data types other than numpy natively. You will therefore have to query the weights and network structure and do the conversion yourself atm. We are in fact working on a tool to facilitate that process but it will not be released anytime soon...

Hope that helps!
Best,
4flixt

**Comment by eivindeb** [comment]
Thanks for the quick response! Okay, so the problem I ran into is that it seems the set_objective requires mterm to be a SX or MX casadi object. If I understand you correctly I can make a function that has the weights from the NN and pass this to the model? E.g.:

def mterm_fun(x_N):
     value = l1_W * x_N + l1_B  # First layer
     value = act(value)              # First layer activation function, e.g. relu
     ....
     return value                        # And this is hopefully still an SX or MX object

And then use mpc.set_objective(mterm=mterm_fun) or a lambda or something like that?

**Comment by eivindeb** [comment]
I found some inspiration here (https://web.casadi.org/blog/tensorflow/) and was able to solve my problem. Closing the issue, thanks for the help!
