### ISSUE TITLE
documentation for the objective function used

### ISSUE THREAD

**Issue by DystopianLphant** [do-mpc/do-mpc#95]
Regarding the documentation on our [do-mpc](do-mpc.com) homepage.

**Link to page / section of the issue** 

[here](https://www.do-mpc.com/en/latest/api/do_mpc.estimator.MHE.set_objective.html?highlight=objective%20function#do_mpc.estimator.MHE.set_objective
) [and here](https://www.do-mpc.com/en/latest/getting_started.html)

**What is wrong / missing?**

the objective function in the getting started example show a form of the objective function that I cannot find elsewhere.
where was it taken from? I need it for my thesis please

**Comment by 4flixt** [comment]
Hi DystopianLphant,

thank you for your question. In the getting started example you are referring to we are configuring an MPC controller. The link you have posted to the documentation is about the cost function of the moving horizon estimator (MHE). Please check the documentation [here](https://www.do-mpc.com/en/latest/api/do_mpc.controller.MPC.set_objective.html). It should look more familiar.

Best regards
4flixt

**Comment by DystopianLphant** [comment]
I actually linked the wrong one. looking "meyer term" or any other keyword related to it I cannot find anything in control books, even specific ones about MPC, so I was wondering where did it come from. the specific doc page doesn't explain much more compared to the formula itself, which isn't a problem for me to understand, I would just like having something to reference and maybe to explain how the special form where the final step cost, meyer term, has different weight. 
I can see that taking that piece off the objective function becomes the one I was thought when I studied linear MPC and the one that appears on some books

**Comment by 4flixt** [comment]
Hi DystopianLphant,

I guess you are right, the terminology isn't extremely common in MPC. I do find some works, however, using these terms ([example](https://www.sciencedirect.com/science/article/pii/S0959152419303592)) in the context of MPC.

Initially, these terms come from optimal control theory but even in that field they aren't always used. Here is an [example](https://www.epfl.ch/labs/la/wp-content/uploads/2018/08/ic-32_lectures-17-28.pdf). 

Regardless of the names, it is very common to have a stage cost (lagrange term) and a terminal cost (mayer term). The terminal cost is part of the terminal ingredients in MPC which are required to show stability. You will find a lot of information in this [book](https://sites.engineering.ucsb.edu/~jbraw/mpc/MPC-book-2nd-edition-3rd-printing.pdf).

Two final remarks: 
- Unfortunately, We have always written "Meyer" term, where it should have been "Mayer" term
- Because it is much more common, we will change the names to ``stage_cost`` and ``terminal_cost`` in the future. 

Best
4flixt
